name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
      - name: print new lines
        run:
          echo Line 1!
          echo Line 2!
          echo Hello world
